cors:
  origin:
    patterns: http://localhost:8080,http://localhost:8081,https://tupi.dev
security:
  jwt:
    token:
      secret-key: 84fds46341fa5e
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  paths-to-match:
   - "/api/v1/**"
   - "/auth/**"
